### ISSUE TITLE
Are graphQL endpoints behind self hosted gateway GA?

### ISSUE THREAD

**Issue by jblaaa-codes** [Azure/api-management-self-hosted-gateway#318] opened 2024-12-03 21:07 UTC
### Discussed in https://github.com/Azure/api-management-self-hosted-gateway/discussions/317

<div type='discussions-op-text'>

<sup>Originally posted by **jblaaa-codes** November 26, 2024</sup>
I see graphQL endpoints added on v2.5.0 #271  in public preview. Is it still in public preview or GA? Thank you.</div>

**Comment by tomkerkhove** [comment] 2024-12-06 09:18
Duplicate of https://github.com/Azure/api-management-self-hosted-gateway/discussions/317 and not a bug

**Closed by tomkerkhove** 2024-12-06 09:18 UTC
