### ISSUE TITLE
Self hostes gateway only use container solution?

### ISSUE THREAD

**Issue by edwardkuo** [Azure/api-management-self-hosted-gateway#144] opened 2022-09-06 00:50 UTC
### Discussed in https://github.com/Azure/api-management-self-hosted-gateway/discussions/143

<div type='discussions-op-text'>

<sup>Originally posted by **edwardkuo** September  5, 2022</sup>
I find the architecture of the API management gateway is very similar to the mulesoft API management. It also uses the Linux containers to do its gateway solution. I ask them if there is any other solution if not the container solution. They also provide the install application solution to do its gateway. I am not sure API management gateway  is a similar solution</div>

**Comment by tomkerkhove** [comment] 2022-09-12 07:01
Duplicate of https://github.com/Azure/api-management-self-hosted-gateway/discussions/143

**Closed by tomkerkhove** 2022-09-12 07:01 UTC
