### ISSUE TITLE
Self-Hosted Gateway Fetching APIs from Both Dev and Production APIM Environments  

### ISSUE THREAD

**Issue by meezankhan9** [Azure/api-management-self-hosted-gateway#309] opened 2024-10-02 15:03 UTC
### Report

Hi all,

We are facing an issue with our self-hosted gateway configuration in Azure API Management. The setup involves a custom domain dev.configuration.api.xyz.com in our Dev APIM environment.

Here’s the situation:

We have configured the self-hosted gateway to work with Dev APIM, specifically using the Dev gateway apim-gw-aws-dev.

However, when connecting to the configuration endpoint dev.configuration.api.xyz.com, we’re seeing not only the Dev APIs but also the routes from our Production APIM (api.xyz.com), which should not be the case.

Expected behavior: It should only return APIs from the Dev gateway (apim-gw-aws-dev).

Microsoft’s Investigation:

We worked with Microsoft on the initial authentication issue, and the connectivity to the Dev APIM has been resolved. Below is an excerpt from the analysis:

“We observed an authorization failure due to an invalid token and attempted to generate a new one. When that didn’t resolve the issue, we switched the authorization to an app registration (ccc_apim-gw-aws-we-dev) as API Management Gateway Configuration Reader Role, which resolved the authentication problem. We are now able to retrieve all Dev APIs as expected."

However, when connecting via the dev.configuration.api.xyz.com endpoint, we are still seeing APIs from the Production environment.

Microsoft’s team has advised reaching out to the GitHub community for further assistance on this issue.

What We Need Help With:

Has anyone encountered this issue where a self-hosted gateway is fetching APIs from both Dev and Production when it should only be fetching from the specified Dev gateway? If so, what could be the cause and solution to restrict the gateway to only return the Dev environment APIs?

Any guidance or pointers would be appreciated!

Thanks,
Meezan

### Expected Behavior

Hi all,

We are facing an issue with our self-hosted gateway configuration in Azure API Management. The setup involves a custom domain dev.configuration.api.xyz.com in our Dev APIM environment.

Here’s the situation:

We have configured the self-hosted gateway to work with Dev APIM, specifically using the Dev gateway apim-gw-aws-dev.

However, when connecting to the configuration endpoint dev.configuration.api.xyz.com, we’re seeing not only the Dev APIs but also the routes from our Production APIM (api.xyz.com), which should not be the case.

Expected behavior: It should only return APIs from the Dev gateway (apim-gw-aws-dev).

Microsoft’s Investigation:

We worked with Microsoft on the initial authentication issue, and the connectivity to the Dev APIM has been resolved. Below is an excerpt from the analysis:

“We observed an authorization failure due to an invalid token and attempted to generate a new one. When that didn’t resolve the issue, we switched the authorization to an app registration (ccc_apim-gw-aws-we-dev) as API Management Gateway Configuration Reader Role, which resolved the authentication problem. We are now able to retrieve all Dev APIs as expected."

However, when connecting via the dev.configuration.api.xyz.com endpoint, we are still seeing APIs from the Production environment.

Microsoft’s team has advised reaching out to the GitHub community for further assistance on this issue.

What We Need Help With:

Has anyone encountered this issue where a self-hosted gateway is fetching APIs from both Dev and Production when it should only be fetching from the specified Dev gateway? If so, what could be the cause and solution to restrict the gateway to only return the Dev environment APIs?

Any guidance or pointers would be appreciated!

Thanks,
Meezan

### Actual Behavior

Hi all,

We are facing an issue with our self-hosted gateway configuration in Azure API Management. The setup involves a custom domain dev.configuration.api.xyz.com in our Dev APIM environment.

Here’s the situation:

We have configured the self-hosted gateway to work with Dev APIM, specifically using the Dev gateway apim-gw-aws-dev.

However, when connecting to the configuration endpoint dev.configuration.api.xyz.com, we’re seeing not only the Dev APIs but also the routes from our Production APIM (api.xyz.com), which should not be the case.

Expected behavior: It should only return APIs from the Dev gateway (apim-gw-aws-dev).

Microsoft’s Investigation:

We worked with Microsoft on the initial authentication issue, and the connectivity to the Dev APIM has been resolved. Below is an excerpt from the analysis:

“We observed an authorization failure due to an invalid token and attempted to generate a new one. When that didn’t resolve the issue, we switched the authorization to an app registration (ccc_apim-gw-aws-we-dev) as API Management Gateway Configuration Reader Role, which resolved the authentication problem. We are now able to retrieve all Dev APIs as expected."

However, when connecting via the dev.configuration.api.xyz.com endpoint, we are still seeing APIs from the Production environment.

Microsoft’s team has advised reaching out to the GitHub community for further assistance on this issue.

What We Need Help With:

Has anyone encountered this issue where a self-hosted gateway is fetching APIs from both Dev and Production when it should only be fetching from the specified Dev gateway? If so, what could be the cause and solution to restrict the gateway to only return the Dev environment APIs?

Any guidance or pointers would be appreciated!

Thanks,
Meezan

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from self-hosted gateway

```
example
```

### Self-hosted Gateway Version

1

### Deployment

Self-Managed (YAML/Helm)

### Platform

Microsoft Azure

### Kubernetes Version

None

**Comment by tomkerkhove** [comment] 2024-10-04 09:14
Duplicate of https://github.com/Azure/api-management-self-hosted-gateway/discussions/308

**Closed by tomkerkhove** 2024-10-04 09:14 UTC
Labels: bug
