### ISSUE TITLE
Error implementing azureAdApp authorization for self hosted gateway

### ISSUE THREAD

**Issue by klakshmikantha** [Azure/api-management-self-hosted-gateway#269] opened 2023-11-28 20:42 UTC
### Discussed in https://github.com/Azure/api-management-self-hosted-gateway/discussions/268

<div type='discussions-op-text'>

<sup>Originally posted by **klakshmikantha** November 28, 2023</sup>
Hi,

I was setting up a self hosted gateway on my docker desktop and while it works using the default 30 day token, I was trying to implement the Entra ID integration based security following the steps in this article - https://learn.microsoft.com/en-us/azure/api-management/self-hosted-gateway-enable-azure-ad
Although the article recommends creating custom role, I added existing API mgt contributor role to SPN (to read configurations) and API mgt reader role to APIM managed identity.
When I re-deploy the docker container with following env variables,
config.service.endpoint=custom_domain
config.service.auth=azureAdApp 
config.service.auth.azureAd.authority=https://login.microsoftonline.com  
config.service.auth.azureAd.tenantId=redacted 
config.service.auth.azureAd.clientId=redacted 
config.service.auth.azureAd.clientSecret=redacted
gateway.name=self-hosted-gateway-name
runtime.deployment.artifact.source=Azure Portal
runtime.deployment.mechanism=Docker
it fails on startup with below error - 
 [Error] [GatewayStartup], message: No valid authentication was configured for the configuration API. The supported authentication model(s) are through gateway tokens, Azure AD application or managed identity.
 [Error] [TenantRecycleFailed], exception: System.Exception: Gateway is unable to start up given it is not properly configured.
   at Gateway.Host.AspNetCore.HostBootstrapper.GetAdditionalTenantSettings() in D:\a\1\s\Proxy\Gateway.App.SelfHosted\HostBootstrapper.cs:line 328
   at Gateway.Host.AspNetCore.HostBootstrapper.StartTenantAsync(CancellationToken cancellation, Boolean initialTenantRecycle) in D:\a\1\s\Proxy\Gateway.App.SelfHosted\HostBootstrapper.cs:line 201
  at Gateway.Host.AspNetCore.HostBootstrapper.RecycleTenantAsync(CancellationToken cancellation, Boolean initialTenantRecycle) in D:\a\1\s\Proxy\Gateway.App.SelfHosted\HostBootstrapper.cs:line 173

Any thoughts on resolving it? Appreciate any help.
</div>

**Comment by tomkerkhove** [comment] 2023-12-01 08:58
Duplicate of https://github.com/Azure/api-management-self-hosted-gateway/discussions/268

**Closed by tomkerkhove** 2023-12-01 08:58 UTC
